theme: jekyll-theme-cayman # do not change this line
description: Amina Kudaibergen, Allen Ramirez, Cephas Osey-Bonsu, Vamsi Chitturi
github:
  repository_url: https://github.com/Breast-Cancer-Detection/Breast-Cancer-Detection
